#ifndef SEARCHRESULTS_H_
#define SEARCHRESULTS_H_

#include <map>

// LET THIS FILE STORE THE OPTIMAL RESULTS AT THE END OF ALGORITHM RUN OR MAY BE 
// DURING THE ALGORITHM ITERATIONS AS WELL

#endif /*SEARCHRESULTS_H_*/
